export const GET_BANNER_IMGS='home/GET_BANNER_IMGS';
export const CHANGE_HOME_DATA='home/CHANGE_HOME_DATA';
export const ADD_ARTICALE_LIST='home/ADD_ARTICALE_LIST';
export const TOGGLE_TOP_SHOW='home/TOGGLE_TOP_SHOW';
export const CHANGE_WRITERS_DATA='home/CHANGE_WRITERS_DATA';
export const CHANGE_WRITER_PAGE='home/CHANGE_WRITER_PAGE';
export const SHOW_CODE='home/SHOW_CODE';
export const DISMISS_CODE='home/DISMISS_CODE';